### PR TITLE
Added Markdown generator.

### PR DESCRIPTION
**Pull request by glenasmith**
Hi Alan,

Not sure if you're interested, or whether it's in scope, but I've created a Markdown generator. I'm in process of moving from Wordpress to a static generator (Hexo) and attributed Markdown images was a missing item in my toolchain!

Thanks for all your great work here. Really helpful.

Glen.

### CODE REVIEW

**Comment by cogdog** [comment]
That is totally cool Glen! I'm on a plane right now but will pull the request asap... it's a great idea.

**Comment by cogdog** [comment]
Hi Glen 

Not sure if reply went through, sent from a plane as wifi went out. M

This is AWESOME! I'll pull the changes as soon as I get back fully online.

**Comment by glenasmith** [comment]
Thanks mate. That's so great!

**Comment by cogdog** [comment]
Thanks for the Markdown version.

**Comment by glenasmith** [comment]
Wow! It's already gone live!

I'll be giving it plenty of use. Thanks again for making it happen!

**Pull request merged**
